"""CE-08 badges: ícono placeholder + nombre real del área en los sub-badges de pilar

Dos arreglos de catálogo para que los badges se puedan mostrar en pantalla
(rediseño colaborador · Partes 3, 4 y 6):

1. **Ícono placeholder** para toda fila de ``badges`` con ``icon_url = ''`` — los
   18 badges de nivel seedeados en CE-04 y los sub-badges de pilar creados por el
   sync de contenido. Sin esto la UI renderiza imágenes vacías. El arte
   definitivo se sube después y solo cambia el ``icon_url``.
2. **Nombre visible del área** en los sub-badges ``pillar-<dim>-<pilar>``, que
   hasta ahora se creaban como ``CP · Pilar P1``. Las 6 áreas de Carrera toman su
   nombre real; el resto cae al mismo fallback que usa la UI (``V1`` → "Etapa V1",
   ``P3`` → "Pilar 3"), para que el nombre guardado y el mostrado coincidan.

   Solo se reescriben los nombres que **siguen siendo autogenerados** (``<DIM> ·
   Pilar <CODE>``): un nombre ya curado a mano nunca se pisa.

Idempotente y re-ejecutable. El downgrade deja los íconos en '' otra vez.

Revision ID: ce08badgeart01
Revises: 2a3c52c9973a
Create Date: 2026-09-07 00:00:00.000000
"""
from __future__ import annotations

import re
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ce08badgeart01"
down_revision: str | None = "2a3c52c9973a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

PLACEHOLDER_ICON = "/icons/badge-placeholder.svg"

# Espejo de `hg.modules.learning_units.pillars.PILLAR_NAMES` (solo Carrera tiene
# nombres definidos hoy). Se replica acá porque una migración no debe importar
# código de la app: el registro puede cambiar y la migración tiene que seguir
# describiendo lo que hizo el día que corrió.
# Nombre autogenerado por el sync: "<DIM> · Pilar <CODE>". Solo estos se reescriben.
_AUTOGENERATED_NAME_RE = re.compile(r"^[A-Z]{2,3} · Pilar \S+$")


def _area_name(dimension: str, pillar: str) -> str:
    """Mismo criterio que ``pillar_display_name`` de la app, replicado acá porque
    una migración no debe importar código que puede cambiar."""
    pillar = pillar.upper()
    if dimension.upper() == "CP" and pillar in CP_AREA_NAMES:
        return CP_AREA_NAMES[pillar]
    if re.fullmatch(r"P\d+", pillar):
        return f"Pilar {pillar[1:]}"
    if re.fullmatch(r"V\d+", pillar):
        return f"Etapa {pillar}"
    if pillar == "AI":
        return "Inteligencia artificial"
    return pillar


CP_AREA_NAMES: dict[str, str] = {
    "P1": "Adaptabilidad de aprendizaje",
    "P2": "Excelencia operativa y colaboración",
    "P3": "Experticia y pensamiento estratégico",
    "P4": "Comunicación e influencia",
    "P5": "Inteligencia emocional y social",
    "AI": "Inteligencia artificial aplicada",
}


def upgrade() -> None:
    bind = op.get_bind()

    # 1. Ícono placeholder donde no hay arte.
    bind.execute(
        sa.text("UPDATE badges SET icon_url = :icon WHERE icon_url IS NULL OR icon_url = ''"),
        {"icon": PLACEHOLDER_ICON},
    )

    # 2. Nombre visible de los sub-badges de área. Solo se tocan los que todavía
    # tienen el nombre autogenerado por el sync ("CP · Pilar P1"): si alguien ya
    # curó el nombre a mano, gana el nombre curado.
    rows = bind.execute(
        sa.text("SELECT code, name FROM badges WHERE code LIKE 'pillar-%'")
    ).all()
    for code, current in rows:
        if not _AUTOGENERATED_NAME_RE.match(current or ""):
            continue
        parts = code.split("-")
        if len(parts) != 3:
            continue
        _, dimension, pillar = parts
        name = _area_name(dimension, pillar)
        bind.execute(
            sa.text(
                "UPDATE badges SET name = :name, description = :desc, unlock_hint = :hint "
                "WHERE code = :code"
            ),
            {
                "name": name,
                "desc": f"Completaste todas las unidades del área {name}.",
                "hint": f"Completá todas las unidades del área {name}.",
                "code": code,
            },
        )


def downgrade() -> None:
    op.execute(
        sa.text("UPDATE badges SET icon_url = '' WHERE icon_url = :icon").bindparams(
            icon=PLACEHOLDER_ICON
        )
    )

    bind = op.get_bind()
    rows = bind.execute(sa.text("SELECT code FROM badges WHERE code LIKE 'pillar-%'")).all()
    for (code,) in rows:
        parts = code.split("-")
        if len(parts) != 3:
            continue
        _, dimension, pillar = parts
        bind.execute(
            sa.text("UPDATE badges SET name = :name WHERE code = :code"),
            {"name": f"{dimension.upper()} · Pilar {pillar.upper()}", "code": code},
        )
